# SPDX-FileCopyrightText: OpenTalk Team <mail@opentalk.eu>
# SPDX-License-Identifier: EUPL-1.2

---
spec:
  inputs:
    release_version:
      description: |
        Version number, e.g. `1.2.3`. Must be in format `<major>.<minor>.<patch>`.
        Keep at `0.0.0` unless you're in the process of creating a release.
      type: string
      regex: ^([0]|([1-9]\d*))\.([0]|([1-9]\d*))\.([0]|([1-9]\d*))$
      default: 0.0.0
    release_issue:
      description: |
        The number of an issue which should be closed by a release MR created by this pipeline.
        Keep empty or unset unless you're in the process of creating a release.
      type: string
      regex: ^\d*$
      default: ''
---
image: git.opentalk.dev:5050/opentalk/backend/containers/rust:1.97.1-trixie

stages:
  - build
  - lint
  - test
  - trigger
  - package
  - release

variables:
  SKOPEO_IMAGE: quay.io/skopeo/stable:v1
  DEFAULT_FLAVOR: alpine

.template_vars:
  FLAVORS: [alpine, trixie, resolute]
  DEFAULT_FLAVOR: alpine

.default_job_condition: &default_job_condition
  needs: []
  rules:
    # Run in merge requests (if there is one job with this instruction, all jobs without
    # it are ignored for the MR pipeline)
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Run on scheduled pipeline runs
    - if: $CI_PIPELINE_SOURCE == 'schedule'

include:
  - project: opentalk/ci/templates/collect-commit-evidence
    ref: v2
    file: .gitlab-ci-template.yml
  - project: opentalk/ci/templates/release-creation
    inputs:
      version: $[[ inputs.release_version ]]
      issue: $[[ inputs.release_issue]]
    ref: v1
    file: .gitlab-ci-template.yml
  - project: opentalk/ci/templates/changelog
    ref: v2
    file: .gitlab-ci-template.yml
  - project: opentalk/ci/templates/rust-lint
    ref: v1
    file: .gitlab-ci-template.yml
  - project: opentalk/ci/templates/common-lint
    ref: v1
    file: .gitlab-ci-template.yml
  - project: opentalk/ci/templates/rust-container-build
    inputs:
      harbor_namespace_suffix: orchestrator
    ref: v2
    file: .gitlab-ci-template.yml

test:cargo_test:
  stage: test
  tags:
    - testcontainers
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  artifacts:
    reports:
      junit: target/nextest/ci/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: target/llvm-cov-target/cobertura.xml
  # this uses region for coverage summary
  coverage: /TOTAL\s+(\d+\s+)+(\d+\.\d+\%)/
  script:
    - cargo llvm-cov nextest --all-features --profile ci
    - cargo llvm-cov report --cobertura --output-path target/llvm-cov-target/cobertura.xml

build:
  stage: build
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG != null
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    VERGEN_GIT_SHA: $CI_COMMIT_SHA
    VERGEN_GIT_BRANCH: $CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - target/release/orchestrator
    expire_in: 1 week
  script:
    - cargo auditable build --all-features --release --locked --workspace
