# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[workspace]
members = ["orchestrator", "orchestrator-shared", "orchestrator-client"]
resolver = "2"

[workspace.package]
authors = ["OpenTalk Team <mail@opentalk.eu>"]
edition = "2024"
homepage = "https://opentalk.eu/"
repository = "https://gitlab.opencode.de/opentalk/orchestrator"
version = "0.1.1"
license = "EUPL-1.2"

[workspace.dependencies]
reqwest = { version = "0.13", default-features = false, features = [
  "json",
  "rustls",
] }
anyhow = "1.0"
async-trait = "0.1"
axum = { version = "0.8", features = ["http2", "ws"] }
bytes = "1.10"
env = "1.0"
futures-util = "0.3"
log = "0.4"
url = "2.5"
opentalk-roomserver-types = "0.0.19"
opentalk-roomserver-web-api = "0.0.19"
opentalk-types = { version = "0.61", default-features = false }
opentalk-types-api-v1 = { version = "0.52", default-features = false, features = [
  "http",
] }
opentalk-types-common = { version = "0.42", default-features = false, features = [
  "serde",
] }
opentalk-types-api-common = "0.6.0"
rand = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
opentalk-orchestrator-shared = { path = "./orchestrator-shared", version = "0.1" }
thiserror = "2.0"
tokio = { version = "1.47", default-features = false }
tokio-tungstenite = { version = "0.28", default-features = false, features = [
  "rustls",
] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tungstenite = { version = "0.28", default-features = false, features = [
  "rustls",
] }
test-log = "0.2"
opentalk-service-auth = "0.1"
config = "0.15"
serde_path_to_error = "0.1"
dirs = "6.0"
clap = { version = "4.5", features = ["derive"] }


[workspace.lints.clippy]
self_named_module_files = "deny"
