# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

FROM rust:slim-trixie AS builder

RUN apt-get update && \
    apt-get full-upgrade -y && \
    apt-get install --no-install-recommends -y ca-certificates pkg-config libssl-dev curl && \
    mkdir /orchestrator

WORKDIR /orchestrator

ADD . /orchestrator

RUN cargo build --release --locked -p opentalk-orchestrator

FROM debian:trixie-slim

RUN apt-get update && \
    apt-get full-upgrade -y && \
    apt-get install --no-install-recommends -y ca-certificates && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir /orchestrator

WORKDIR /orchestrator

ENV USERID=1000
ENV GROUPID=1000

COPY --from=builder /orchestrator/target/release/opentalk-orchestrator .

USER $USERID:$GROUPID

EXPOSE 11222
ENTRYPOINT [ "./opentalk-orchestrator" ]
