# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-orchestrator-shared"
description = "Shared types for orchestrated services"
version = "0.4.2"
publish = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lib]

[features]
default = []
recording-service = []
roomserver-service = []
transcription-service = []

[dependencies]
opentalk-service-auth.workspace = true
opentalk-types-common = { version = "0.43", features = ["serde"] }
serde.workspace = true
thiserror.workspace = true
url.workspace = true

[lints]
workspace = true
