# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "orchestrator"
description = "OpenTalk Orchestrator Service"
version.workspace = true
publish = false
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
url.workspace = true
clap.workspace = true
axum.workspace = true
bytes.workspace = true
log.workspace = true
opentalk-roomserver-types.workspace = true
service-probe.workspace = true
service-probe-client.workspace = true
opentalk-roomserver-web-api.workspace = true
opentalk-types-common.workspace = true
opentalk-types-api-common = { workspace = true, features = ["http", "serde"] }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
opentalk-orchestrator-shared = { workspace = true, features = [
  "recording-service",
  "roomserver-service",
  "transcription-service",
] }
tokio = { workspace = true, features = [
  "macros",
  "rt-multi-thread",
  "sync",
  "signal",
] }
tracing-subscriber.workspace = true
opentalk-service-auth = { workspace = true, features = ["axum"] }
thiserror.workspace = true
config.workspace = true
serde_path_to_error.workspace = true
dirs.workspace = true

[dev-dependencies]
test-log.workspace = true

[lints]
workspace = true
