// SPDX-License-Identifier: EUPL-1.2
// SPDX-FileCopyrightText: OpenTalk Team <mail@opentalk.eu>

//! The token store for roomserver signaling sessions
//!
//! In order to proxy roomserver signaling sessions, the orchestrator needs to map tokens to their
//! designated roomserver instance. The tokens are generated by the roomserver and saved by the
//! orchestrator when they get returned to client.
use std::{
    collections::{BTreeSet, HashMap},
    time::{Duration, Instant},
};

use opentalk_types_common::{rooms::RoomId, roomserver::Token};

// Longer default expiry than the default roomserver expiry. This avoids having tokens expire in the
// orchestrator before they do in the roomserver
const DEFAULT_EXPIRY: Duration = Duration::from_secs(60);

/// Information about a token and when it was created
///
/// Used to determine if a token has expired
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
struct TokenExpiry {
    created_at: Instant,
    token: Token,
}

impl TokenExpiry {
    fn new_now(token: Token) -> Self {
        Self {
            created_at: Instant::now(),
            token,
        }
    }
}

/// Manages the active signaling tokens of the Roomserver
///
/// Expired tokens get cleaned up when the [`TokenStore`] is accessed
#[derive(Debug)]
pub struct TokenStore {
    /// The active tokens
    tokens: HashMap<Token, RoomId>,
    /// A set to track the expiry of each token
    expiry_set: BTreeSet<TokenExpiry>,
    /// The duration for that a token is active
    expiry: Duration,
}

impl Default for TokenStore {
    fn default() -> Self {
        Self::new()
    }
}

impl TokenStore {
    pub fn new() -> Self {
        Self::new_with_expiry(DEFAULT_EXPIRY)
    }

    pub fn new_with_expiry(expiry: Duration) -> Self {
        Self {
            tokens: HashMap::new(),
            expiry_set: BTreeSet::new(),
            expiry,
        }
    }

    pub fn add_token(&mut self, room_id: RoomId, token: Token) -> anyhow::Result<()> {
        self.remove_expired_entries();

        if let Some(room) = self.tokens.insert(token, room_id) {
            anyhow::bail!("UUID collision, token {token} already exists for room {room}");
        }

        self.expiry_set.insert(TokenExpiry::new_now(token));

        Ok(())
    }

    pub fn consume_token(&mut self, token: &Token) -> Option<RoomId> {
        self.remove_expired_entries();
        self.tokens.remove(token)
    }

    fn remove_expired_entries(&mut self) {
        let now = Instant::now();

        while let Some(&entry) = self.expiry_set.first() {
            let duration_since_creation = now.duration_since(entry.created_at);

            if duration_since_creation >= self.expiry {
                self.expiry_set.remove(&entry);
                self.tokens.remove(&entry.token);
            } else {
                // The oldest key is not yet expired
                return;
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use std::{
        thread,
        time::{Duration, Instant},
    };

    use opentalk_types_common::{rooms::RoomId, roomserver::Token};

    use super::{TokenExpiry, TokenStore};

    #[test]
    fn test_expiry() {
        let mut store = TokenStore::new_with_expiry(Duration::from_millis(500));

        let room1 = RoomId::from_u128(1);
        let token1 = Token::generate();
        store.add_token(room1, token1).unwrap();

        let room2 = RoomId::from_u128(2);
        let token2 = Token::generate();
        store.add_token(room2, token2).unwrap();

        // get the right room for token1
        assert_eq!(store.consume_token(&token1), Some(room1));
        // ensure the token was consumed
        assert_eq!(None, store.consume_token(&token1));

        thread::sleep(Duration::from_millis(750));

        //ensure the second token expired
        assert_eq!(None, store.consume_token(&token2));
    }

    /// The sorting of [Token] depends on the order of the structs fields. This
    /// test shall ensure that the tokens are ordered by created-at time first.
    #[test]
    fn test_token_sorting() {
        let tokens = [
            // expired tokens
            TokenExpiry {
                token: Token::from_u128(5),
                created_at: Instant::now().checked_sub(Duration::from_secs(63)).unwrap(),
            },
            TokenExpiry {
                token: Token::from_u128(4),
                created_at: Instant::now().checked_sub(Duration::from_secs(62)).unwrap(),
            },
            TokenExpiry {
                token: Token::from_u128(3),
                created_at: Instant::now().checked_sub(Duration::from_secs(61)).unwrap(),
            },
            // valid tokens
            TokenExpiry {
                token: Token::from_u128(2),
                created_at: Instant::now().checked_add(Duration::from_secs(61)).unwrap(),
            },
            TokenExpiry {
                token: Token::from_u128(1),
                created_at: Instant::now().checked_add(Duration::from_secs(62)).unwrap(),
            },
            TokenExpiry {
                token: Token::from_u128(0),
                created_at: Instant::now().checked_add(Duration::from_secs(63)).unwrap(),
            },
        ]
        .to_vec();
        let mut sorted_tokens = tokens.clone();
        sorted_tokens.sort();

        assert_eq!(sorted_tokens, tokens);
    }
}
