# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "opentalk-orchestrator-client"
description = "Client for orchestrated services"
version = "0.1.0"
publish = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lib]

[features]
default = []
recording-service = ["opentalk-orchestrator-shared/recording-service"]
roomserver-service = ["opentalk-orchestrator-shared/roomserver-service"]
transcription-service = ["opentalk-orchestrator-shared/transcription-service"]

[dependencies]
anyhow.workspace = true
bytes.workspace = true
futures-util.workspace = true
log.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
opentalk-orchestrator-shared.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [
  "macros",
  "rt-multi-thread",
  "sync",
  "time",
] }
tokio-tungstenite = { workspace = true, features = ["connect", "handshake"] }
async-trait.workspace = true
url.workspace = true

[build-dependencies]
anyhow = "1"
