// SPDX-License-Identifier: EUPL-1.2
// SPDX-FileCopyrightText: OpenTalk Team <mail@opentalk.eu>

//! The token store for roomserver signaling sessions
//!
//! In order to proxy roomserver signaling sessions, the orchestrator needs to map tokens to their
//! designated roomserver instance. The tokens are generated by the roomserver and saved by the
//! orchestrator when they get returned to client.
use std::{
    collections::{BTreeSet, HashMap},
    time::{Duration, Instant},
};

use opentalk_types_common::{rooms::RoomId, roomserver::Token};

use crate::storage::ROOMSERVER_TOKEN_EXPIRY;

/// Holds the signaling tokens of the Roomserver and their expiry information
#[derive(Debug)]
pub(crate) struct LocalTokenStore {
    /// The active tokens
    pub(crate) tokens: HashMap<Token, RoomId>,
    /// A set to track the expiry of each token
    pub(crate) expiry_set: BTreeSet<TokenExpiry>,
    /// The duration that a token is active for
    pub(crate) expiry: Duration,
}

impl Default for LocalTokenStore {
    fn default() -> Self {
        Self::new()
    }
}

impl LocalTokenStore {
    pub fn new() -> Self {
        Self::new_with_expiry(ROOMSERVER_TOKEN_EXPIRY)
    }

    pub fn new_with_expiry(expiry: Duration) -> Self {
        Self {
            tokens: HashMap::new(),
            expiry_set: BTreeSet::new(),
            expiry,
        }
    }

    pub fn remove_expired_entries(&mut self) {
        let now = Instant::now();

        while let Some(&entry) = self.expiry_set.first() {
            let duration_since_creation = now.duration_since(entry.created_at);

            if duration_since_creation >= self.expiry {
                self.expiry_set.remove(&entry);
                self.tokens.remove(&entry.token);
            } else {
                // The oldest key is not yet expired
                return;
            }
        }
    }
}

/// Information about a token and when it was created
///
/// Used to determine if a token has expired
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub(crate) struct TokenExpiry {
    pub(crate) created_at: Instant,
    pub(crate) token: Token,
}

impl TokenExpiry {
    pub(crate) fn new_now(token: Token) -> Self {
        Self {
            created_at: Instant::now(),
            token,
        }
    }
}

#[cfg(test)]
mod tests {
    use std::time::{Duration, Instant};

    use opentalk_types_common::roomserver::Token;

    use super::TokenExpiry;

    /// The local token storage implementation relies on the ordering of tokens by expiry (oldest
    /// first).
    ///
    /// This test ensures that the tokens are ordered by created-at time first.
    #[test]
    fn test_token_ordering() {
        let tokens = [
            // expired tokens
            TokenExpiry {
                token: Token::from_u128(5),
                created_at: Instant::now().checked_sub(Duration::from_secs(63)).unwrap(),
            },
            TokenExpiry {
                token: Token::from_u128(4),
                created_at: Instant::now().checked_sub(Duration::from_secs(62)).unwrap(),
            },
            TokenExpiry {
                token: Token::from_u128(3),
                created_at: Instant::now().checked_sub(Duration::from_secs(61)).unwrap(),
            },
            // valid tokens
            TokenExpiry {
                token: Token::from_u128(2),
                created_at: Instant::now().checked_add(Duration::from_secs(61)).unwrap(),
            },
            TokenExpiry {
                token: Token::from_u128(1),
                created_at: Instant::now().checked_add(Duration::from_secs(62)).unwrap(),
            },
            TokenExpiry {
                token: Token::from_u128(0),
                created_at: Instant::now().checked_add(Duration::from_secs(63)).unwrap(),
            },
        ]
        .to_vec();
        let mut sorted_tokens = tokens.clone();
        sorted_tokens.sort();

        assert_eq!(sorted_tokens, tokens);
    }
}
